import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import LogoImg from "../../public/images/logo.png";
import Link from "next/link";
import { useInView } from "react-intersection-observer";
import { useEffect, useState } from "react";
import FirstSectionBook from "../../public/images/img-one.png";
import SecondSectionBook from "../../public/images/img-two.png";
import ThirdSectionBook from "../../public/images/img-three.png";
import FourthSectionBook from "../../public/images/img-four.png";
import FifthSectionBook from "../../public/images/img-five.png";

// const sections = ['firstSection', 'secondSection', 'thirdSection', 'fourthSection', 'fifthSection'];
const sections = [
  { linkName: "firstSection", title: "Issue #5" },
  { linkName: "secondSection", title: "Issue #4" },
  { linkName: "thirdSection", title: "Issue #3" },
  { linkName: "fourthSection", title: "Issue #2" },
  { linkName: "fifthSection", title: "Issue #1" },
];

const Home: NextPage = () => {
  const options = {
    threshold: 0.5,
  };

  const { ref: firstSectionRef, inView: firstInView, entry: firstEntry } = useInView(options);
  const { ref: secondSectionRef, inView: secondInView, entry: secondEntry } = useInView(options);
  const { ref: thirdSectionRef, inView: thirdInView, entry: thirdEntry } = useInView(options);
  const { ref: fourthSectionRef, inView: fourthInView, entry: fourthEntry } = useInView(options);
  const { ref: fifthSectionRef, inView: fifthInView, entry: fifthEntry } = useInView(options);

  const [pageClass, setPageClass] = useState("firstSection");

  useEffect(() => {
    // console.log({ firstInView, secondInView, thirdInView, fourthInView, fifthInView });
    if (firstInView) {
      setPageClass("firstSection");
    } else if (secondInView) {
      setPageClass("secondSection");
    } else if (thirdInView) {
      setPageClass("thirdSection");
    } else if (fourthInView) {
      setPageClass("fourthSection");
    } else if (fifthInView) {
      setPageClass("fifthSection");
    }
  }, [firstInView, secondInView, thirdInView, fourthInView, fifthInView]);

  return (
    <div className={`${styles.container} ${pageClass}`}>
      <Head>
        <title>Backstage Talks Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <div className={styles.title}>
          <Image alt="logo" src={LogoImg} className="img" />
        </div>
      </header>

      <main className={styles.main}>
        <div className={styles.mainContainer}>
          <section id="firstSection" ref={firstSectionRef}>
            <div>
              <div className={styles.imgContainer}>
                <Image src={FirstSectionBook} alt="issue-5-book-image" className="img" />
              </div>
              <p>Issue #5</p>
              <Link href="#">
                <a>BUY HERE</a>
              </Link>
              <p>
                or in{" "}
                <Link href="#">
                  <a>selected stores</a>
                </Link>
              </p>
            </div>
          </section>
          <section id="secondSection" ref={secondSectionRef}>
            <div>
              <div className={styles.imgContainer}>
                <Image src={SecondSectionBook} alt="issue-5-book-image" className="img" />
              </div>
              <p>Issue #4</p>
              <Link href="#">
                <a>BUY HERE</a>
              </Link>
              <p>
                or in{" "}
                <Link href="#">
                  <a>selected stores</a>
                </Link>
              </p>
            </div>
          </section>
          <section id="thirdSection" ref={thirdSectionRef}>
            <div>
              <div className={styles.imgContainer}>
                <Image src={ThirdSectionBook} alt="issue-5-book-image" className="img" />
              </div>
              <p>Issue #3</p>
              <Link href="#">
                <a>BUY HERE</a>
              </Link>
              <p>
                or in{" "}
                <Link href="#">
                  <a>selected stores</a>
                </Link>
              </p>
            </div>
          </section>
          <section id="fourthSection" ref={fourthSectionRef}>
            <div>
              <div className={styles.imgContainer}>
                <Image src={FourthSectionBook} alt="issue-5-book-image" className="img" />
              </div>
              <p>Issue #2</p>
              <Link href="#">
                <a>BUY HERE</a>
              </Link>
              <p>
                or in{" "}
                <Link href="#">
                  <a>selected stores</a>
                </Link>
              </p>
            </div>
          </section>
          <section id="fifthSection" ref={fifthSectionRef}>
            <div>
              <div className={styles.imgContainer}>
                <Image src={FifthSectionBook} alt="issue-5-book-image" className="img" />
              </div>
              <p>Issue #1</p>
              <Link href="#">
                <a>BUY HERE</a>
              </Link>
              <p>
                or in{" "}
                <Link href="#">
                  <a>selected stores</a>
                </Link>
              </p>
            </div>
          </section>
        </div>
      </main>

      <section className={styles.info}>
        <p>info@backstagetalks.com</p>
      </section>

      <section className={styles.anchors}>
        {sections.map((item) => (
          <Link href={`#${item.linkName}`} key={item.linkName}>
            <a className={pageClass === item.linkName ? "activeLink" : ""}>{item.title}</a>
          </Link>
        ))}
      </section>

      <footer className={styles.footer}>
        <div className={styles.footerContainer}>
          <p>
            Backstage Talks is a magazine of casual, but in depth dialogues on design and business.
            Our decisions shape and influence this complex world—to have a chance to make the right
            ones, we need to talk.
          </p>
          <p>&copy; 2022 Published by Studio Milk and cloned by Egbedokun Olayinka</p>
          <Link href="#">
            <a>Privacy Policy</a>
          </Link>
          <p>info@backstagetalks.com</p>
        </div>
      </footer>

      <style jsx global>{`
        body,
        html {
          margin: 0;
          height: 100%;
        }
        html {
          scroll-behavior: smooth;
        }
      `}</style>
    </div>
  );
};

export default Home;
